### PR TITLE
#7 - add support for regexp into split and dotted profile field names

### PR DESCRIPTION
**Pull request by jpahullo**
This addresses issue  #7

### CODE REVIEW

**Comment by jpahullo** [comment]
We will check the errors of the CI, but I think it would be nice to have comments from you.

**Comment by jpahullo** [comment]
rebased to the latest main branch

**Comment by jpahullo** [comment]
now its CI is green too.

**Comment by jpahullo** [comment]
Thanks @danmarsden for passing by this PR and point to MOODLE_403_STABLE branch of this plugin.

What do you think about this patch? We have it in production for years without any trouble. By now, we only have this value on the setting `local_cohortauto | mainrule_fld`:

```
%split(profile.cohortstoenrol|;)
```

We have a process that generates the list of cohorts that the user has to be enrolled in. Then, this plugin local_cohortauto with this setting builds up to as many cohorts as possible values there, and enrolles the user to all cohorts in that custom profile field.

That is, imagina user with that custom setting with value: `cohort name 1;cohort name 2; cohort name 5;` When local_cohortauto enters into play, it ensures all 3 cohorts with that name exists (i.e., cohort "cohort name 1", and cohort "cohort name 2" and cohort "cohort name 5") and then enrols the given user to all 3 cohorts.

At least for us, this funcionality is very convenient and necessary, since we have a single custom profile field where we calculate the name of all the cohorts the user must belong to. 

Thanks,

Jordi

**Comment by danmarsden** [comment]
thanks Jordi - I hadn't merged this becauase I wanted to test a particular use-case of the filter and make sure this change didn't break it, but that particular use case isn't something we use here anymore so I've just merged this in!

**Pull request merged**
