### PR TITLE
#31 - remove ->context warning on login

### PR DESCRIPTION
**Pull request by jpahullo**

### CODE REVIEW

**Comment by jpahullo** [comment]
This is to fix #31. With this patch, we do not see the warning shown on #31 anymore.

**Comment by jpahullo** [comment]
rebased to the latest main branch

**Comment by danmarsden** [comment]
Hi @jpahullo looks sensible and I've merged it in - thanks!

**Comment by jpahullo** [comment]
Thanks @danmarsden ! It is a pleasure to contribute into it. Thank you for your support!

**Pull request merged**
